### ISSUE TITLE
Non-deterministic ProcessExecutionDetector

### ISSUE THREAD

**Issue by bannsec** [S2E/libs2eplugins#13]
Ref #10 -- I have rebuilt my setup and I have some new findings.

The changes made in that PR appear to have helped. Previously, I could not hit a break point in the amd64 PIE binary through ProcessExectuionDetector (see other ticket for more information). I now can hit the callback but only _randomly_.

I have run a test case where it is a very basic amd64 PIE ELF binary, and I attempt to set an instruction hook at the entry point to main. I found this address statically, and am using the documented S2E hooks to get a callback on the translation of this address.

My test simply involved outputting a message if the translation callback was hit during execution. My test code looks like:

```python
import subprocess

count = 0
for _ in range(100):
    if "Avoiding address" in subprocess.check_output(["./launch-s2e.sh"]):
        count += 1
```

In 100 tests, _exactly_ 50 of them successfully got the translation callback. The other 50 did not.

**Comment by adrianherrera** [comment]
Hmm interesting. Can you post your plugin code? Without being able to run it myself, the only thing I can think of is that ASLR is enabled and the address is changing - can you check your logs to see if the binary is being loaded at the same address each time?

**Comment by Owlz** [comment]
Sure thing. The official plugin code is checked into my github:

https://github.com/Owlz/s2e/blob/master/plugins/AvoidAddress.md
https://github.com/Owlz/s2e/blob/master/plugins/AvoidAddress.cpp
https://github.com/Owlz/s2e/blob/master/plugins/AvoidAddress.h

Checking the logs, it definitely is ASLR'd and being loaded and unique addresses each time. That said, my plugin is supposed to be able to handle that. Perhaps I made a silly logic mistake in it though. Would love a second set of eyes :-)

**Comment by adrianherrera** [comment]
Cool, thanks for that! I'll have a look at your plugin code.

In the mean time, can you just disable ASLR (you should be able to do something like `echo 0 | sudo tee /proc/sys/kernel/randomize_va_space` in the bootstrap script) and see if you get 100% success?
