### ISSUE TITLE
How to compile the s2e plugin?

### ISSUE THREAD

**Issue by danchou-ssr** [S2E/libs2eplugins#60]
I have configured the s2e-config.lua file as follows:

add_plugin("InstructionTracker")
pluginsConfig.InstructionTracker = {
    -- The address we want to track
    addressToTrack = 0x12345,
}

The plugin code path is in &s2eDir/libs2eplugins/src/s2e/Plugins. When I call launch-s2e.sh, the program reminds me that I have not found the plugin. The error message is as follows:

Starting libs2e...
Opening /dev/kvm
Initializing qemu32-s2e cpu
S2E: output directory = "./s2e-out-9"
Revision: 00a9296df84bf27a9d7bb65301540ed8b633818f
Config date: June 09, 2019 Sunday 12:49:59 CST

Lua: attempting to load models.lua
[Z3] Initializing
Using module /home/fire/s2e/install/share/libs2e/op_helper.bc.i386
Current data layout: e-m:e-i64:64-f80:128-n8:16:32:64-S128
Current target triple:
BEGIN searcher description
DFSSearcher
END searcher description
Using log level override 'debug'
Setting console level to 'debug'
Creating plugin CorePlugin
ERROR: plugin 'InstructionTracker' does not exist in this S2E installation

**Comment by vitalych** [comment]
Did you write the plugin yourself? It's not part of S2E at least. Available tracers are here:
https://github.com/S2E/libs2eplugins/tree/master/src/s2e/Plugins/ExecutionTracers

**Comment by danchou-ssr** [comment]
> Did you write the plugin yourself? It's not part of S2E at least. Available tracers are here:
> https://github.com/S2E/libs2eplugins/tree/master/src/s2e/Plugins/ExecutionTracers

I wrote according to the tutorial, it is here:
http://s2e.systems/docs/Howtos/WritingPlugins.html

**Comment by danchou-ssr** [comment]
This issue has been resolved!
